services:
    localDB:
        image: postgres:13
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${PASS}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "5432:5432"
        volumes:
            - "./db-data:/var/lib/postgresql/data"

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGA_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PASS}
        ports:
            - "8081:80"
        depends_on:
            - "localDB"


    metabase:
        image: metabase/metabase
        environment:
            MB_DB_TYPE: postgres
            MB_DB_HOST: localDB
            MB_DB_PORT: 5432
            MB_DB_DBNAME: ${DB_NAME}
            MB_DB_USER: ${DB_USER}  
            MB_DB_PASS: ${PASS}
        ports:
            - "3000:3000"
        depends_on:
            - "localDB"

